// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPublishedArticles = `-- name: CountPublishedArticles :one
SELECT COUNT(*) FROM articles
WHERE status = 'published'
`

func (q *Queries) CountPublishedArticles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedArticles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (title, slug, summary, content, category_id, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, slug, summary, content, category_id, status, view_count, published_at, created_at, updated_at
`

type CreateArticleParams struct {
	Title      string      `json:"title"`
	Slug       string      `json:"slug"`
	Summary    pgtype.Text `json:"summary"`
	Content    string      `json:"content"`
	CategoryID pgtype.UUID `json:"category_id"`
	Status     string      `json:"status"`
}

type CreateArticleRow struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Summary     pgtype.Text      `json:"summary"`
	Content     string           `json:"content"`
	CategoryID  pgtype.UUID      `json:"category_id"`
	Status      string           `json:"status"`
	ViewCount   int32            `json:"view_count"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (CreateArticleRow, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Title,
		arg.Slug,
		arg.Summary,
		arg.Content,
		arg.CategoryID,
		arg.Status,
	)
	var i CreateArticleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.Content,
		&i.CategoryID,
		&i.Status,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, title, slug, summary, content, category_id, status, view_count, published_at, created_at, updated_at
FROM articles
WHERE id = $1
`

type GetArticleByIDRow struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Summary     pgtype.Text      `json:"summary"`
	Content     string           `json:"content"`
	CategoryID  pgtype.UUID      `json:"category_id"`
	Status      string           `json:"status"`
	ViewCount   int32            `json:"view_count"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetArticleByID(ctx context.Context, id pgtype.UUID) (GetArticleByIDRow, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i GetArticleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.Content,
		&i.CategoryID,
		&i.Status,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT id, title, slug, summary, content, category_id, status, view_count, published_at, created_at, updated_at
FROM articles
WHERE slug = $1 AND status = 'published'
`

type GetArticleBySlugRow struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Summary     pgtype.Text      `json:"summary"`
	Content     string           `json:"content"`
	CategoryID  pgtype.UUID      `json:"category_id"`
	Status      string           `json:"status"`
	ViewCount   int32            `json:"view_count"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i GetArticleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.Content,
		&i.CategoryID,
		&i.Status,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementViewCount = `-- name: IncrementViewCount :exec
UPDATE articles
SET view_count = view_count + 1
WHERE id = $1
`

func (q *Queries) IncrementViewCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementViewCount, id)
	return err
}

const listAllArticles = `-- name: ListAllArticles :many
SELECT id, title, slug, summary, content, category_id, status, view_count, published_at, created_at, updated_at
FROM articles
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllArticlesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllArticlesRow struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Summary     pgtype.Text      `json:"summary"`
	Content     string           `json:"content"`
	CategoryID  pgtype.UUID      `json:"category_id"`
	Status      string           `json:"status"`
	ViewCount   int32            `json:"view_count"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListAllArticles(ctx context.Context, arg ListAllArticlesParams) ([]ListAllArticlesRow, error) {
	rows, err := q.db.Query(ctx, listAllArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllArticlesRow{}
	for rows.Next() {
		var i ListAllArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.Content,
			&i.CategoryID,
			&i.Status,
			&i.ViewCount,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByCategory = `-- name: ListArticlesByCategory :many
SELECT id, title, slug, summary, content, category_id, status, view_count, published_at, created_at, updated_at
FROM articles
WHERE status = 'published' AND category_id = $1
ORDER BY published_at DESC
LIMIT $2 OFFSET $3
`

type ListArticlesByCategoryParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListArticlesByCategoryRow struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Summary     pgtype.Text      `json:"summary"`
	Content     string           `json:"content"`
	CategoryID  pgtype.UUID      `json:"category_id"`
	Status      string           `json:"status"`
	ViewCount   int32            `json:"view_count"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListArticlesByCategory(ctx context.Context, arg ListArticlesByCategoryParams) ([]ListArticlesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listArticlesByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByCategoryRow{}
	for rows.Next() {
		var i ListArticlesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.Content,
			&i.CategoryID,
			&i.Status,
			&i.ViewCount,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticles = `-- name: ListPublishedArticles :many
SELECT id, title, slug, summary, content, category_id, status, view_count, published_at, created_at, updated_at
FROM articles
WHERE status = 'published'
ORDER BY published_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedArticlesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPublishedArticlesRow struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Summary     pgtype.Text      `json:"summary"`
	Content     string           `json:"content"`
	CategoryID  pgtype.UUID      `json:"category_id"`
	Status      string           `json:"status"`
	ViewCount   int32            `json:"view_count"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListPublishedArticles(ctx context.Context, arg ListPublishedArticlesParams) ([]ListPublishedArticlesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedArticlesRow{}
	for rows.Next() {
		var i ListPublishedArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.Content,
			&i.CategoryID,
			&i.Status,
			&i.ViewCount,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishArticle = `-- name: PublishArticle :exec
UPDATE articles
SET status = 'published', published_at = NOW()
WHERE id = $1
`

func (q *Queries) PublishArticle(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, publishArticle, id)
	return err
}

const unpublishArticle = `-- name: UnpublishArticle :exec
UPDATE articles
SET status = 'draft', published_at = NULL
WHERE id = $1
`

func (q *Queries) UnpublishArticle(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unpublishArticle, id)
	return err
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET title = $2, slug = $3, summary = $4, content = $5, category_id = $6, status = $7
WHERE id = $1
RETURNING id, title, slug, summary, content, category_id, status, view_count, published_at, created_at, updated_at
`

type UpdateArticleParams struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	Slug       string      `json:"slug"`
	Summary    pgtype.Text `json:"summary"`
	Content    string      `json:"content"`
	CategoryID pgtype.UUID `json:"category_id"`
	Status     string      `json:"status"`
}

type UpdateArticleRow struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Summary     pgtype.Text      `json:"summary"`
	Content     string           `json:"content"`
	CategoryID  pgtype.UUID      `json:"category_id"`
	Status      string           `json:"status"`
	ViewCount   int32            `json:"view_count"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (UpdateArticleRow, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Summary,
		arg.Content,
		arg.CategoryID,
		arg.Status,
	)
	var i UpdateArticleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.Content,
		&i.CategoryID,
		&i.Status,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
