// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article_tag.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addArticleTag = `-- name: AddArticleTag :exec
INSERT INTO article_tags (article_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddArticleTagParams struct {
	ArticleID pgtype.UUID `json:"article_id"`
	TagID     pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AddArticleTag(ctx context.Context, arg AddArticleTagParams) error {
	_, err := q.db.Exec(ctx, addArticleTag, arg.ArticleID, arg.TagID)
	return err
}

const getArticleTags = `-- name: GetArticleTags :many
SELECT t.id, t.name, t.slug, t.created_at FROM tags t
INNER JOIN article_tags at ON t.id = at.tag_id
WHERE at.article_id = $1
ORDER BY t.name
`

func (q *Queries) GetArticleTags(ctx context.Context, articleID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getArticleTags, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagArticles = `-- name: GetTagArticles :many
SELECT a.id, a.title, a.slug, a.summary, a.content, a.category_id, a.status, a.view_count, a.published_at, a.created_at, a.updated_at
FROM articles a
INNER JOIN article_tags at ON a.id = at.article_id
WHERE at.tag_id = $1 AND a.status = 'published'
ORDER BY a.published_at DESC
LIMIT $2 OFFSET $3
`

type GetTagArticlesParams struct {
	TagID  pgtype.UUID `json:"tag_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetTagArticlesRow struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Summary     pgtype.Text      `json:"summary"`
	Content     string           `json:"content"`
	CategoryID  pgtype.UUID      `json:"category_id"`
	Status      string           `json:"status"`
	ViewCount   int32            `json:"view_count"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetTagArticles(ctx context.Context, arg GetTagArticlesParams) ([]GetTagArticlesRow, error) {
	rows, err := q.db.Query(ctx, getTagArticles, arg.TagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTagArticlesRow{}
	for rows.Next() {
		var i GetTagArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.Content,
			&i.CategoryID,
			&i.Status,
			&i.ViewCount,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllArticleTags = `-- name: RemoveAllArticleTags :exec
DELETE FROM article_tags
WHERE article_id = $1
`

func (q *Queries) RemoveAllArticleTags(ctx context.Context, articleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeAllArticleTags, articleID)
	return err
}

const removeArticleTag = `-- name: RemoveArticleTag :exec
DELETE FROM article_tags
WHERE article_id = $1 AND tag_id = $2
`

type RemoveArticleTagParams struct {
	ArticleID pgtype.UUID `json:"article_id"`
	TagID     pgtype.UUID `json:"tag_id"`
}

func (q *Queries) RemoveArticleTag(ctx context.Context, arg RemoveArticleTagParams) error {
	_, err := q.db.Exec(ctx, removeArticleTag, arg.ArticleID, arg.TagID)
	return err
}
