// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveComment = `-- name: ApproveComment :exec
UPDATE comments
SET approved = true
WHERE id = $1
`

func (q *Queries) ApproveComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, approveComment, id)
	return err
}

const countAllComments = `-- name: CountAllComments :one
SELECT COUNT(*) FROM comments
`

func (q *Queries) CountAllComments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllComments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCommentsByArticle = `-- name: CountCommentsByArticle :one
SELECT COUNT(*) FROM comments
WHERE article_id = $1 AND approved = true
`

func (q *Queries) CountCommentsByArticle(ctx context.Context, articleID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByArticle, articleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentCommentsByIP = `-- name: CountRecentCommentsByIP :one
SELECT COUNT(*) FROM comments
WHERE ip_address = $1 AND created_at > $2
`

type CountRecentCommentsByIPParams struct {
	IpAddress pgtype.Text      `json:"ip_address"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CountRecentCommentsByIP(ctx context.Context, arg CountRecentCommentsByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentCommentsByIP, arg.IpAddress, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (article_id, session_id, nickname, content, ip_address, parent_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, article_id, session_id, nickname, content, ip_address, parent_id, approved, created_at
`

type CreateCommentParams struct {
	ArticleID pgtype.UUID `json:"article_id"`
	SessionID pgtype.UUID `json:"session_id"`
	Nickname  string      `json:"nickname"`
	Content   string      `json:"content"`
	IpAddress pgtype.Text `json:"ip_address"`
	ParentID  pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ArticleID,
		arg.SessionID,
		arg.Nickname,
		arg.Content,
		arg.IpAddress,
		arg.ParentID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.SessionID,
		&i.Nickname,
		&i.Content,
		&i.IpAddress,
		&i.ParentID,
		&i.Approved,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, article_id, session_id, nickname, content, ip_address, parent_id, approved, created_at FROM comments
WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id pgtype.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.SessionID,
		&i.Nickname,
		&i.Content,
		&i.IpAddress,
		&i.ParentID,
		&i.Approved,
		&i.CreatedAt,
	)
	return i, err
}

const listAllComments = `-- name: ListAllComments :many
SELECT c.id, c.article_id, c.session_id, c.nickname, c.content, c.ip_address, c.parent_id, c.approved, c.created_at, a.title as article_title, a.slug as article_slug
FROM comments c
INNER JOIN articles a ON c.article_id = a.id
ORDER BY c.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllCommentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllCommentsRow struct {
	ID           pgtype.UUID      `json:"id"`
	ArticleID    pgtype.UUID      `json:"article_id"`
	SessionID    pgtype.UUID      `json:"session_id"`
	Nickname     string           `json:"nickname"`
	Content      string           `json:"content"`
	IpAddress    pgtype.Text      `json:"ip_address"`
	ParentID     pgtype.UUID      `json:"parent_id"`
	Approved     bool             `json:"approved"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	ArticleTitle string           `json:"article_title"`
	ArticleSlug  string           `json:"article_slug"`
}

func (q *Queries) ListAllComments(ctx context.Context, arg ListAllCommentsParams) ([]ListAllCommentsRow, error) {
	rows, err := q.db.Query(ctx, listAllComments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCommentsRow{}
	for rows.Next() {
		var i ListAllCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.SessionID,
			&i.Nickname,
			&i.Content,
			&i.IpAddress,
			&i.ParentID,
			&i.Approved,
			&i.CreatedAt,
			&i.ArticleTitle,
			&i.ArticleSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByArticle = `-- name: ListCommentsByArticle :many
SELECT id, article_id, session_id, nickname, content, ip_address, parent_id, approved, created_at FROM comments
WHERE article_id = $1 AND parent_id IS NULL AND approved = true
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListCommentsByArticleParams struct {
	ArticleID pgtype.UUID `json:"article_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListCommentsByArticle(ctx context.Context, arg ListCommentsByArticleParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByArticle, arg.ArticleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.SessionID,
			&i.Nickname,
			&i.Content,
			&i.IpAddress,
			&i.ParentID,
			&i.Approved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByArticleAdmin = `-- name: ListCommentsByArticleAdmin :many
SELECT id, article_id, session_id, nickname, content, ip_address, parent_id, approved, created_at FROM comments
WHERE article_id = $1 AND parent_id IS NULL
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListCommentsByArticleAdminParams struct {
	ArticleID pgtype.UUID `json:"article_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListCommentsByArticleAdmin(ctx context.Context, arg ListCommentsByArticleAdminParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByArticleAdmin, arg.ArticleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.SessionID,
			&i.Nickname,
			&i.Content,
			&i.IpAddress,
			&i.ParentID,
			&i.Approved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByArticleWithSession = `-- name: ListCommentsByArticleWithSession :many
SELECT id, article_id, session_id, nickname, content, ip_address, parent_id, approved, created_at FROM comments
WHERE article_id = $1
  AND parent_id IS NULL
  AND (approved = true OR session_id = $2)
ORDER BY created_at ASC
LIMIT $3 OFFSET $4
`

type ListCommentsByArticleWithSessionParams struct {
	ArticleID pgtype.UUID `json:"article_id"`
	SessionID pgtype.UUID `json:"session_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListCommentsByArticleWithSession(ctx context.Context, arg ListCommentsByArticleWithSessionParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByArticleWithSession,
		arg.ArticleID,
		arg.SessionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.SessionID,
			&i.Nickname,
			&i.Content,
			&i.IpAddress,
			&i.ParentID,
			&i.Approved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepliesByComment = `-- name: ListRepliesByComment :many
SELECT id, article_id, session_id, nickname, content, ip_address, parent_id, approved, created_at FROM comments
WHERE parent_id = $1 AND approved = true
ORDER BY created_at ASC
`

func (q *Queries) ListRepliesByComment(ctx context.Context, parentID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listRepliesByComment, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.SessionID,
			&i.Nickname,
			&i.Content,
			&i.IpAddress,
			&i.ParentID,
			&i.Approved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepliesByCommentWithSession = `-- name: ListRepliesByCommentWithSession :many
SELECT id, article_id, session_id, nickname, content, ip_address, parent_id, approved, created_at FROM comments
WHERE parent_id = $1 AND (approved = true OR session_id = $2)
ORDER BY created_at ASC
`

type ListRepliesByCommentWithSessionParams struct {
	ParentID  pgtype.UUID `json:"parent_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) ListRepliesByCommentWithSession(ctx context.Context, arg ListRepliesByCommentWithSessionParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listRepliesByCommentWithSession, arg.ParentID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.SessionID,
			&i.Nickname,
			&i.Content,
			&i.IpAddress,
			&i.ParentID,
			&i.Approved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
