// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: homepage.sql

package db

import (
	"context"
)

const createDefaultHomepageSettings = `-- name: CreateDefaultHomepageSettings :one
INSERT INTO homepage_settings (
    hero_title,
    hero_subtitle,
    hero_cta_text,
    hero_cta_link,
    about_title,
    about_content
) VALUES (
    'Welcome',
    'Your digital space',
    'Explore',
    '/articles',
    'About',
    'Tell your story here'
)
RETURNING id, hero_title, hero_subtitle, hero_cta_text, hero_cta_link, about_title, about_content, updated_at
`

func (q *Queries) CreateDefaultHomepageSettings(ctx context.Context) (HomepageSetting, error) {
	row := q.db.QueryRow(ctx, createDefaultHomepageSettings)
	var i HomepageSetting
	err := row.Scan(
		&i.ID,
		&i.HeroTitle,
		&i.HeroSubtitle,
		&i.HeroCtaText,
		&i.HeroCtaLink,
		&i.AboutTitle,
		&i.AboutContent,
		&i.UpdatedAt,
	)
	return i, err
}

const getHomepageSettings = `-- name: GetHomepageSettings :one
SELECT id, hero_title, hero_subtitle, hero_cta_text, hero_cta_link, about_title, about_content, updated_at FROM homepage_settings
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetHomepageSettings(ctx context.Context) (HomepageSetting, error) {
	row := q.db.QueryRow(ctx, getHomepageSettings)
	var i HomepageSetting
	err := row.Scan(
		&i.ID,
		&i.HeroTitle,
		&i.HeroSubtitle,
		&i.HeroCtaText,
		&i.HeroCtaLink,
		&i.AboutTitle,
		&i.AboutContent,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHomepageSettings = `-- name: UpsertHomepageSettings :one
INSERT INTO homepage_settings (
    hero_title,
    hero_subtitle,
    hero_cta_text,
    hero_cta_link,
    about_title,
    about_content
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (id) DO UPDATE SET
    hero_title = EXCLUDED.hero_title,
    hero_subtitle = EXCLUDED.hero_subtitle,
    hero_cta_text = EXCLUDED.hero_cta_text,
    hero_cta_link = EXCLUDED.hero_cta_link,
    about_title = EXCLUDED.about_title,
    about_content = EXCLUDED.about_content,
    updated_at = NOW()
RETURNING id, hero_title, hero_subtitle, hero_cta_text, hero_cta_link, about_title, about_content, updated_at
`

type UpsertHomepageSettingsParams struct {
	HeroTitle    string `json:"hero_title"`
	HeroSubtitle string `json:"hero_subtitle"`
	HeroCtaText  string `json:"hero_cta_text"`
	HeroCtaLink  string `json:"hero_cta_link"`
	AboutTitle   string `json:"about_title"`
	AboutContent string `json:"about_content"`
}

func (q *Queries) UpsertHomepageSettings(ctx context.Context, arg UpsertHomepageSettingsParams) (HomepageSetting, error) {
	row := q.db.QueryRow(ctx, upsertHomepageSettings,
		arg.HeroTitle,
		arg.HeroSubtitle,
		arg.HeroCtaText,
		arg.HeroCtaLink,
		arg.AboutTitle,
		arg.AboutContent,
	)
	var i HomepageSetting
	err := row.Scan(
		&i.ID,
		&i.HeroTitle,
		&i.HeroSubtitle,
		&i.HeroCtaText,
		&i.HeroCtaLink,
		&i.AboutTitle,
		&i.AboutContent,
		&i.UpdatedAt,
	)
	return i, err
}
