// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countImages = `-- name: CountImages :one
SELECT COUNT(*) FROM images
WHERE ($1::text = '' OR folder = $1)
`

func (q *Queries) CountImages(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countImages, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImage = `-- name: CreateImage :one
INSERT INTO images (
    filename,
    original_filename,
    url,
    folder,
    alt_text,
    size_bytes,
    mime_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, filename, original_filename, url, folder, alt_text, size_bytes, mime_type, created_at
`

type CreateImageParams struct {
	Filename         string      `json:"filename"`
	OriginalFilename string      `json:"original_filename"`
	Url              string      `json:"url"`
	Folder           string      `json:"folder"`
	AltText          pgtype.Text `json:"alt_text"`
	SizeBytes        int64       `json:"size_bytes"`
	MimeType         string      `json:"mime_type"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.Filename,
		arg.OriginalFilename,
		arg.Url,
		arg.Folder,
		arg.AltText,
		arg.SizeBytes,
		arg.MimeType,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalFilename,
		&i.Url,
		&i.Folder,
		&i.AltText,
		&i.SizeBytes,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images
WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteImage, id)
	return err
}

const getImage = `-- name: GetImage :one
SELECT id, filename, original_filename, url, folder, alt_text, size_bytes, mime_type, created_at FROM images
WHERE id = $1
`

func (q *Queries) GetImage(ctx context.Context, id pgtype.UUID) (Image, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalFilename,
		&i.Url,
		&i.Folder,
		&i.AltText,
		&i.SizeBytes,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const listImages = `-- name: ListImages :many
SELECT id, filename, original_filename, url, folder, alt_text, size_bytes, mime_type, created_at FROM images
WHERE ($1::text = '' OR folder = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListImagesParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListImages(ctx context.Context, arg ListImagesParams) ([]Image, error) {
	rows, err := q.db.Query(ctx, listImages, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.OriginalFilename,
			&i.Url,
			&i.Folder,
			&i.AltText,
			&i.SizeBytes,
			&i.MimeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByFolder = `-- name: ListImagesByFolder :many
SELECT id, filename, original_filename, url, folder, alt_text, size_bytes, mime_type, created_at FROM images
WHERE folder = $1
ORDER BY created_at DESC
`

func (q *Queries) ListImagesByFolder(ctx context.Context, folder string) ([]Image, error) {
	rows, err := q.db.Query(ctx, listImagesByFolder, folder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.OriginalFilename,
			&i.Url,
			&i.Folder,
			&i.AltText,
			&i.SizeBytes,
			&i.MimeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImageAltText = `-- name: UpdateImageAltText :exec
UPDATE images
SET alt_text = $1
WHERE id = $2
`

type UpdateImageAltTextParams struct {
	AltText pgtype.Text `json:"alt_text"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateImageAltText(ctx context.Context, arg UpdateImageAltTextParams) error {
	_, err := q.db.Exec(ctx, updateImageAltText, arg.AltText, arg.ID)
	return err
}
