// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID           pgtype.UUID      `json:"id"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	Email        string           `json:"email"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	LastLoginAt  pgtype.Timestamp `json:"last_login_at"`
}

type Article struct {
	ID           pgtype.UUID      `json:"id"`
	Title        string           `json:"title"`
	Slug         string           `json:"slug"`
	Summary      pgtype.Text      `json:"summary"`
	Content      string           `json:"content"`
	CategoryID   pgtype.UUID      `json:"category_id"`
	Status       string           `json:"status"`
	ViewCount    int32            `json:"view_count"`
	PublishedAt  pgtype.Timestamp `json:"published_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	SearchVector string           `json:"search_vector"`
}

type ArticleTag struct {
	ArticleID pgtype.UUID      `json:"article_id"`
	TagID     pgtype.UUID      `json:"tag_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Category struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Slug        string           `json:"slug"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Comment struct {
	ID        pgtype.UUID      `json:"id"`
	ArticleID pgtype.UUID      `json:"article_id"`
	SessionID pgtype.UUID      `json:"session_id"`
	Nickname  string           `json:"nickname"`
	Content   string           `json:"content"`
	IpAddress pgtype.Text      `json:"ip_address"`
	ParentID  pgtype.UUID      `json:"parent_id"`
	Approved  bool             `json:"approved"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type HomepageSetting struct {
	ID           pgtype.UUID      `json:"id"`
	HeroTitle    string           `json:"hero_title"`
	HeroSubtitle string           `json:"hero_subtitle"`
	HeroCtaText  string           `json:"hero_cta_text"`
	HeroCtaLink  string           `json:"hero_cta_link"`
	AboutTitle   string           `json:"about_title"`
	AboutContent string           `json:"about_content"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Image struct {
	ID               pgtype.UUID      `json:"id"`
	Filename         string           `json:"filename"`
	OriginalFilename string           `json:"original_filename"`
	Url              string           `json:"url"`
	Folder           string           `json:"folder"`
	AltText          pgtype.Text      `json:"alt_text"`
	SizeBytes        int64            `json:"size_bytes"`
	MimeType         string           `json:"mime_type"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type Session struct {
	ID           pgtype.UUID      `json:"id"`
	SessionToken string           `json:"session_token"`
	Nickname     pgtype.Text      `json:"nickname"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Tag struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Slug      string           `json:"slug"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
