// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchArticles = `-- name: SearchArticles :many
SELECT
    id, title, slug, summary,
    category_id, view_count, published_at, created_at,
    ts_rank(search_vector, to_tsquery('english', $1)) as rank
FROM articles
WHERE status = 'published'
    AND search_vector @@ to_tsquery('english', $1)
ORDER BY rank DESC, published_at DESC
LIMIT $2 OFFSET $3
`

type SearchArticlesParams struct {
	ToTsquery string `json:"to_tsquery"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type SearchArticlesRow struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Summary     pgtype.Text      `json:"summary"`
	CategoryID  pgtype.UUID      `json:"category_id"`
	ViewCount   int32            `json:"view_count"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	Rank        float32          `json:"rank"`
}

func (q *Queries) SearchArticles(ctx context.Context, arg SearchArticlesParams) ([]SearchArticlesRow, error) {
	rows, err := q.db.Query(ctx, searchArticles, arg.ToTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchArticlesRow{}
	for rows.Next() {
		var i SearchArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.CategoryID,
			&i.ViewCount,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
