// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (session_token)
VALUES ($1)
RETURNING id, session_token, nickname, created_at, updated_at
`

func (q *Queries) CreateSession(ctx context.Context, sessionToken string) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, sessionToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionToken,
		&i.Nickname,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, session_token, nickname, created_at, updated_at FROM sessions
WHERE session_token = $1
`

func (q *Queries) GetSessionByToken(ctx context.Context, sessionToken string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, sessionToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionToken,
		&i.Nickname,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionNickname = `-- name: UpdateSessionNickname :exec
UPDATE sessions
SET nickname = $1, updated_at = NOW()
WHERE session_token = $2
`

type UpdateSessionNicknameParams struct {
	Nickname     pgtype.Text `json:"nickname"`
	SessionToken string      `json:"session_token"`
}

func (q *Queries) UpdateSessionNickname(ctx context.Context, arg UpdateSessionNicknameParams) error {
	_, err := q.db.Exec(ctx, updateSessionNickname, arg.Nickname, arg.SessionToken)
	return err
}
